#!/usr/bin/env bash
# Takes in a sub-domain and/or a domain and describes it
# shellcheck disable=SC2086

describer() {
    SUB_DOMAIN=$1
    RECORD_TYPE=$(dig $1 | awk '/^[^;]/ {print $4}')
    DESTINATION=$(dig $1 | awk '/^[^;]/ {print $5}')
    echo The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION
}

if [ $# -eq 1 ]; then
    describer www.$1
    describer lb-01.$1
    describer web-01.$1
    describer web-02.$1
else
    describer $2.$1
fi