#!/usr/bin/env bash
# Installs nginx on web-01 server
#
# 1)    sudo apt install nginx
# 2)    delete /etc/nginx/sites-enabled/default
# 3)    make directory /var/www/site1
# 4)    create file /var/www/site1/index.html with "Hello World"
# 5)    create .conf file in /etc/nginx/conf.d
#           - listen on port 80
#           - set root to /var/www/site1
#           - set index
# 6)    nginx -s reload

#1
sudo apt -y update
sudo apt -y install nginx

#2
sudo rm /etc/nginx/sites-enabled/default

#3
sudo mkdir /var/www/site1

#4
echo "Hello World" | sudo tee /var/www/site1/index.html > /dev/null

#5
echo "server{
	listen 80;
	root /var/www/site1;
	index index.html;
}" | sudo tee /etc/nginx/conf.d/site1.conf > /dev/null

#6
sudo service nginx restart