#!/usr/bin/env bash
# Installs nginx on web-01 server
#
# 1)    sudo apt install nginx
# 2)    delete /etc/nginx/sites-enabled/default
# 3)    make directory /var/www/site1
# 4)    create file /var/www/site1/index.html with "Hello World"
# 5)    create .conf file in /etc/nginx/conf.d
#           - listen on port 80
#           - set root to /var/www/site1
#           - set index
# 6)    nginx -s reload

#1
apt -y update
apt -y install nginx

#2
rm /etc/nginx/sites-enabled/default

#3
mkdir /var/www/tacobell

#4
echo "Hello World" > /var/www/tacobell/index.html

#5
echo "server{
	listen 80;
	root /var/www/tacobell;
	index index.html;
}" > /etc/nginx/conf.d/tacobell.conf

#6
service nginx restart