#!/usr/bin/env bash
# Change nginx to listen on port 80 and restart
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
printf '#!/bin/bash\necho " "\* nginx is not running\n' > /etc/init.d/nginx
sudo service nginx restart
