#!/usr/bin/env bash
# Configure server to run nginx as user nginx listening on port 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 666 /etc/nginx/sites-enabled/default
chmod 666 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
